version: 2
jobs:
  build:
    working_directory: ~/dots
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}

      - run:
        name: Install dependencies
        command: npm install

      - run:
        name: Tests
        command: npm run test


