version: 2
jobs:
  node:
    working_directory: ~/dots
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}

      - run:
        name: Install dependencies
        command: npm install

      - run:
        name: Tests
        command: npm run test

  build:
    working_directory: ~/dots
      docker:
          - image: circleci/node:8
      steps:
        - checkout
        - run:
          name: Build project
          command: npm run build

workflows:
  version: 2
  node-build:
    jobs:
      - node
      - build


